### ISSUE TITLE
Error in workflow with large files but file got uploaded to slack

### ISSUE THREAD

**Issue by prashant-flobiz** [MeilCli/slack-upload-file#372]
## Description
Timeout for large files of size around 55 MB, but file got uploaded to slack channel. The status in GitHub action should be a success instead of failure if file gets uploaded successfully.

## Screenshot
<img width="785" alt="Screenshot 2022-02-19 at 8 18 21 PM" src="https://user-images.githubusercontent.com/95214143/154805866-4ba2b753-9001-4106-81c5-ec78cf5a8b5c.png">

**Comment by MeilCli** [comment]
@prashant-flobiz 
A similar issue was raised a while ago.
ref: #362 

Currently, this problem is API-side.
I have one workaround. It's call `files.list` for check if upload was successful when catch 408 error.
But, Its workaround needs additional oauth permission scope `files:read`.
(Currently, this action needs only `files:write`)

Therefore, I hesitate to judge if I want to implement workarounds.

On the other hands, you can solve the problem to use other way.
`steps.continue-on-error` option is useful this problem.
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error
```yml
# example
- uses: MeilCli/slack-upload-file@v1
  continue-on-error: true
  with:
     # args...
```


Could you try `steps.continue-on-error` option?

**Comment by prashant-flobiz** [comment]
Thanks @MeilCli for the suggestion 👍 . I've tried this argument and working fine.
